version: "3.8"


services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    command: ["go", "run", "./cmd/server"]
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db


volumes:
  db_data: